server:
  port: 8082

name: yuxiaoyi

# 对象
person:
  name: ${name}
  age: 20
  #数组
  address:
    - beijing
    - shanghai
    - shengzheng
    - guangzhou

people: {name: zhangyong, age: 29}

msg_1: "hello world! \n yuxiaoyi on it."
msg_2: 'hello world! \n yuxiaoyi not on it.'
